### Test root route
GET http://localhost:3001/

### Get all contacts
GET http://localhost:3001/contacts

### Get a single contact by ID
# Replace <CONTACT_ID> with an actual _id from your DB
GET http://localhost:3001/contacts/695e00f2d55b5f75c3ba5e2b

### Update Contact
# Replace <CONTACT_ID> with an actual _id
PUT http://localhost:3001/contacts/695e0f2d55b5f75c3ba5e2b
Content-Type: application/json

{
    "firstName": "Jane",
    "lastName": "Smith",
    "email": "jane@example.com",
    "favoriteColor": "Red",
    "birthday": "1992-05-15"
}

### Create Contact
POST http://localhost:3001/contacts
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "email": "john@example.com",
    "favoriteColor": "Blue",
    "birthday": "1990-01-01"
}

### Delete Contact
# Replace <CONTACT_ID> with an actual _id
DELETE http://localhost:3001/contacts/696b4c34294fc9ce5cc80310
